# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sinsun_robot/robot_state.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class robot_state(genpy.Message):
  _md5sum = "3dcf316e4e53981483352b964db6e5f9"
  _type = "sinsun_robot/robot_state"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64[] currentFlangePostion
float64[] currentFlangePostionRight
float64[] axisCurrentAngle
float64[] axisCurrentAngleRight
"""
  __slots__ = ['currentFlangePostion','currentFlangePostionRight','axisCurrentAngle','axisCurrentAngleRight']
  _slot_types = ['float64[]','float64[]','float64[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       currentFlangePostion,currentFlangePostionRight,axisCurrentAngle,axisCurrentAngleRight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(robot_state, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.currentFlangePostion is None:
        self.currentFlangePostion = []
      if self.currentFlangePostionRight is None:
        self.currentFlangePostionRight = []
      if self.axisCurrentAngle is None:
        self.axisCurrentAngle = []
      if self.axisCurrentAngleRight is None:
        self.axisCurrentAngleRight = []
    else:
      self.currentFlangePostion = []
      self.currentFlangePostionRight = []
      self.axisCurrentAngle = []
      self.axisCurrentAngleRight = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.currentFlangePostion)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.currentFlangePostion))
      length = len(self.currentFlangePostionRight)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.currentFlangePostionRight))
      length = len(self.axisCurrentAngle)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.axisCurrentAngle))
      length = len(self.axisCurrentAngleRight)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.axisCurrentAngleRight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.currentFlangePostion = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.currentFlangePostionRight = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.axisCurrentAngle = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.axisCurrentAngleRight = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.currentFlangePostion)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.currentFlangePostion.tostring())
      length = len(self.currentFlangePostionRight)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.currentFlangePostionRight.tostring())
      length = len(self.axisCurrentAngle)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.axisCurrentAngle.tostring())
      length = len(self.axisCurrentAngleRight)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.axisCurrentAngleRight.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.currentFlangePostion = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.currentFlangePostionRight = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.axisCurrentAngle = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.axisCurrentAngleRight = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
