(cl:in-package sinsun_robot-msg)
(cl:export '(CURRENTFLANGEPOSTION-VAL
          CURRENTFLANGEPOSTION
          CURRENTFLANGEPOSTIONRIGHT-VAL
          CURRENTFLANGEPOSTIONRIGHT
          AXISCURRENTANGLE-VAL
          AXISCURRENTANGLE
          AXISCURRENTANGLERIGHT-VAL
          AXISCURRENTANGLERIGHT
))